apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: microservices
  labels:
    app: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: 256056679502.dkr.ecr.eu-north-1.amazonaws.com/admin@sha256:3c3ce01e8651e2209eb38ffc8e9c0ad095cb8166e5917a42e6191a1eb42c9229
          ports:
            - containerPort: 3001
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: NEXT_PUBLIC_CLERK_SECRET_KEY
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
            - name: NEXT_PUBLIC_PRODUCT_SERVICE_URL
              value: http://product-service:8000
            - name: NEXT_PUBLIC_ORDER_SERVICE_URL
              value: http://order-service:8001
            - name: NEXT_PUBLIC_PAYMENT_SERVICE_URL
              value: http://payment-service:8002
            - name: NEXT_PUBLIC_AUTH_SERVICE_URL
              value: http://auth-service:8003
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: microservices
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
