# --- ADMIN APP ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: admin
          image: 256056679502.dkr.ecr.eu-north-1.amazonaws.com/admin@sha256:4ad6bafe1699729245e70419321efd059807145931f66567666781c2c3b81bf3
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 3001
          resources:
            requests: { memory: "150Mi", cpu: "200m" }
            limits: { memory: "300Mi", cpu: "800m" }
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: microservices
spec:
  type: NodePort # FIX: NodePort for external access
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 3001 # Cluster Port
      targetPort: 3001
      nodePort: 30005

# --- CLIENT APP ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: client
          image: 256056679502.dkr.ecr.eu-north-1.amazonaws.com/client@sha256:58e902dd2448cb0fa6e815570ce302a70b0a9e67885f8b67f4d89ef84e6bcfce
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 3000
          resources:
            requests: { memory: "150Mi", cpu: "200m" }
            limits: { memory: "300Mi", cpu: "800m" }
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30004 # EXTERNAL ACCESS PORT
