apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  # Postgres done
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: qwerty
  POSTGRES_DB: products
  DATABASE_URL: postgresql://admin:qwerty@postgres:5432/products?schema=public

  # MongoDB (Order service) done
  MONGO_URL: mongodb+srv://faisalrazaqazi2000:8VmPLVQzNzokJx5p@dld.ayf4ikn.mongodb.net/orders?retryWrites=true&w=majority&appName=DLD

  # Clerk done
  CLERK_PUBLISHABLE_KEY: pk_test_ZWxlY3RyaWMtZWxlcGhhbnQtNzIuY2xlcmsuYWNjb3VudHMuZGV2JA
  CLERK_SECRET_KEY: sk_test_kGX9jYo4oHxcBzHVck6Se0zRWmjlAfdCaocwewgQDj

  # Stripe done
  STRIPE_SECRET_KEY: sk_test_51QHMTbJkrqo5V2TDpQiuKA8OCuj1zOQhGhvLjiTxHMcWhshK4apFt5uOJTi9lURLdQoxvrJoGq4bwdRx965RncLH003M5Q1YMt
  STRIPE_WEBHOOK_SECRET: whsec_99KtQTNe4PSbwbodHsgVnDAaN1Fs6lMp

  # Google (Email service) done
  GOOGLE_CLIENT_ID: 693792317203-3fhhv6ih3vr0gmc5aqtn7u6nir2dgrjr.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_REFRESH_TOKEN: 1//04G4L5HV0kA72CgYIARAAGAQSNwF-L9IrAPtBe3MT51TK0cbOeDbfWwicI79ZWzpGwPABvz6Cd9Hz3tbnbyU55iupvl_GaB18oKA

  # Next.js admin & Client
  # services
  NEXT_PUBLIC_PRODUCT_SERVICE_URL: http://localhost:8000
  NEXT_PUBLIC_ORDER_SERVICE_URL: http://localhost:8001
  NEXT_PUBLIC_PAYMENT_SERVICE_URL: http://localhost:8002
  NEXT_PUBLIC_AUTH_SERVICE_URL: http://localhost:8003
  # clerk
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_ZWxlY3RyaWMtZWxlcGhhbnQtNzIuY2xlcmsuYWNjb3VudHMuZGV2JA
  NEXT_PUBLIC_CLERK_SECRET_KEY: sk_test_kGX9jYo4oHxcBzHVck6Se0zRWmjlAfdCaocwewgQDj
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: /
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: /
  #cloud name
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: faisalraza

  KAFKA_BROKERS: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092"
