name: Build & Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # PRODUCT SERVICE
      - name: Build & Push Product Service
        run: |
          docker build -f apps/product-service/Dockerfile -t product-service .
          docker tag product-service:1.0 ${{ secrets.ECR_REGISTRY }}/product-service:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/product-service:1.0

      # AUTH SERVICE
      - name: Build & Push Auth Service
        run: |
          docker build -f apps/auth-service/Dockerfile -t auth-service .
          docker tag auth-service:1.0 ${{ secrets.ECR_REGISTRY }}/auth-service:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/auth-service:1.0

      # ORDER SERVICE
      - name: Build & Push Order Service
        run: |
          docker build -f apps/order-service/Dockerfile -t order-service .
          docker tag order-service:1.0 ${{ secrets.ECR_REGISTRY }}/order-service:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/order-service:1.0

      # PAYMENT SERVICE
      - name: Build & Push Payment Service
        run: |
          docker build -f apps/payment-service/Dockerfile -t payment-service .
          docker tag payment-service:1.0 ${{ secrets.ECR_REGISTRY }}/payment-service:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/payment-service:1.0

      # EMAIL SERVICE
      - name: Build & Push Email Service
        run: |
          docker build -f apps/email-service/Dockerfile -t email-service .
          docker tag email-service:1.0 ${{ secrets.ECR_REGISTRY }}/email-service:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/email-service:1.0

      # CLIENT APP
      - name: Build & Push Client App
        run: |
          docker build -f apps/client/Dockerfile -t client .
          docker tag client:1.0 ${{ secrets.ECR_REGISTRY }}/client:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/client:1.0

      # ADMIN APP
      - name: Build & Push Admin App
        run: |
          docker build -f apps/Admin/Dockerfile -t admin .
          docker tag admin:1.0 ${{ secrets.ECR_REGISTRY }}/admin:1.0
          docker push ${{ secrets.ECR_REGISTRY }}/admin:1.0
